import server from '@/config/server'
let indexServer = server('/v1/:params1/:params2/:params3/:params4/:params5',{},{
  infoList:{
    method:'get',
    params:{
      params1:'front',
      params2:'info',
      params3:'recommend',
      params4:1,
      params5:10
    }
  },
  policyList:{
    method:'post',
    params:{
      params1:'front',
      params2:'policy',
      params3:'search',
      params4:1,
      params5:5
    }
  },
  policyList2:{
    method:'get',
    params:{
      params1:'front',
      params2:'policy',
      params3:'recommend',
      params4:1,
      params5:5
    }
  },
  searchInfo:{
    method:'post',
    params:{
      params1:'front',
      params2:'info',
      params3:'search',
      params4:1,
      params5:5
    }
  },
  orgList:{
    method:'post',
    params:{
      params1:'front',
      params2:'org',
      params3:'find',
      params4:1,
      params5:10,
    }
  },
  loanProductList:{
    method:'get',
    params:{
      params1:'front',
      params2:'loanProduct',
      params3:'recommend',
      params4:1,
      params5:9
    }
  },
  loanProductList2:{
    method:'post',
    params:{
      params1:'front',
      params2:'loanProduct',
      params3:'find',
      params4:1,
      params5:3
    }
  },
  //login
  login:{
    method:'post',
    params:{
      params1:'login'
    }
  },
  //register
  register:{
    method:'post',
    params:{
      params1:'user',
      params2:'register',
    }
  },
  companyRegister:{
    method:'post',
    params:{
      params1:'company',
      params2:'register',
    }
  },
  //verify
  getCode:{
    method:'get',
    params:{
      params1:'verify',
      params2:'getCode'
    }
  },
  getDivisionChildren:{
    method:'get',
    params:{
      params1:'division',
      params2:'children',
    }
  },
  divisionDetails:{
    method:'get',
    params:{
      params1:'division',
      params2:'detail',
    }
  },
  //upload
  upload:{
    method:'post',
    params:{
      params1:'file',
      params2:'upload',
    }
  },
  //根据id拿到所有子集区县
  findAllChildsTree:{
    method:'get',
    params:{
      params1:'division',
      params2:'findAllChildsTree',
    }
  },
  //查询动态展示贷款历史信息
  listDynamic:{
    method:'post',
    params:{
      params1:'loanDone',
      params2:'listDynamic',
    }
  },
  //分页查询农场列表
  farmList:{
    method:'post',
    params:{
      params1:'front',
      params2:'farm',
      params3:'find',
    }
  },
  //分页查询龙头企业列表
  farmList1:{
    method:'post',
    params:{
      params1:'leadingEnterprise',
      params2:'list',
    }
  },
  //分页查询合作社列表
  farmList2:{
    method:'post',
    params:{
      params1:'cooperation',
      params2:'list',
    }
  },
  out:{
    method:'get',
    params:{
      params1:'logout',
    }
  },
  resetPasswd:{
    method:'post',
    params:{
      params1:'account',
      params2:'resetPasswd',
    }
  },
  Statistics:{
    method:'get',
    params:{
      params1:'toCounty',
      params2:'Statistics',
    }
  },
  companyDetails:{
    method:'get',
    params:{
      params1:'front',
      params2:'company',
      params3:'detail',
    }
  },
  personDetails:{
    method:'get',
    params:{
      params1:'person',
      params2:'findByUserId',
    }
  },
  companyUpdate:{
    method:'post',
    params:{
      params1:'front',
      params2:'company',
      params3:'update',
    }
  },
  personUpdate:{
    method:'post',
    params:{
      params1:'person',
      params2:'update',
    }
  },
  bindWx:{
    method:'post',
    params:{
      params1:'bindThirdAccount',
    }
  },
  getMsg:{
    method:'get',
    params:{
      params1:'getLoginSuccessInfo',
    }
  },
  findBaoXian:{
    method:'post',
    params:{
      params1:'front',
      params2:'insureProduct',
      params3:'find',
    }
  },
  getVillageInfoCollect:{
    method:'get',
    params:{
      params1:'statistics',
      params2:'villageInfo',
      params3:'getVillageInfoCollect',
    }
  },
});
export default indexServer
