/**
 * Created by chenchen on 2017/9/4.
 * interface 0.0.1
 */
import server from '@/config/server';
let infoServer = server('/v1/:params1/:params2/:params3/:params4/:params5',{},{
    searchNews:{
      method:'post',
      params:{
        params1:'info',
        params2:'search'
      }
    },
    addNews:{
        method:'post',
        params:{
          params1:'info',
          params2:'add'
        }
    },
    editNews:{
        method:'post',
        params:{
          params1:'info',
          params2:'update'
        }
    },
    deleteNews:{
        method:'post',
        params:{
          params1:'info',
          params2:'delete'
        }
    },
    getNewsDetail:{
        method:'get',
        params:{
          params1:'info',
          params2:'detail'
        }
    },
    searchPolicy:{
        method:'post',
        params:{
          params1:'policy',
          params2:'search'
        }
      },
    addPolicy:{
          method:'post',
          params:{
            params1:'policy',
            params2:'add'
          }
      },
    editPolicy:{
          method:'post',
          params:{
            params1:'policy',
            params2:'update'
          }
      },
    deletePolicy:{
          method:'post',
          params:{
            params1:'policy',
            params2:'delete'
          }
      },
    getPolicyDetail:{
        method:'get',
        params:{
          params1:'policy',
          params2:'detail'
        }
    },


    searchRecommend:{
        method:'post',
        params:{
          params1:'recommend',
          params2:'list'
        }
      },
    addRecommend:{
            method:'post',
            params:{
              params1:'recommend',
              params2:'add'
            }
        },
    editRecommend:{
            method:'post',
            params:{
              params1:'recommend',
              params2:'update'
            }
        },
    deleteRecommend:{
            method:'post',
            params:{
              params1:'recommend',
              params2:'delete'
            }
        },
    sortRecommend:{
            method:'post',
            params:{
              params1:'recommend',
              params2:'sort'
            }
        },
});
export default infoServer;